### ISSUE TITLE
"IsCPUSupported function has not been overriden" message after patch KB4103718 

### ISSUE THREAD

**Issue by AtakSnajpera** [p-lider/WuaCpuFix#1]
Event viewer shows **WuaCpuFix: IsCPUSupported function has not been overriden** and Windows Update is blocked again

https://i.imgur.com/kcPdu5o.png

**Comment by p-lider** [comment]
I have just updated the tool to reflect recent Windows Update changes. Please download the newest version (0.1.2) and the Windows Update should work again.

Issue has been fixed in commit b8e559123c1b93b3396631cef5d91e98b4aa8617.
